services:
  apache:
    image: php:8.1-apache
    container_name: apache_web
    ports:
      - "8082:80"
    volumes:
      - ./content:/var/www/html


  mysql:
    image: mysql:9.3
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: midb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"


