---
- name: Configurar servidor con Docker y lanzar Apache + MySQL
  hosts: dockerhost
  become: true

  tasks:
    - name: Instalar dependencias básicas
      apt:
        name: [apt-transport-https, ca-certificates, curl, software-properties-common]
        update_cache: yes

    - name: Agregar GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Instalar Docker y Docker Compose
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-compose]
        state: present
        update_cache: yes

    - name: Crear directorio del proyecto
      file:
        path: /srv/docker/web
        state: directory

    - name: Copiar docker-compose.yml al servidor
      copy:
        src: docker-compose.yml
        dest: /srv/docker/web/docker-compose.yml

    - name: Copiar carpeta web al servidor
      copy:
        src: content/
        dest: /srv/docker/web/content/
        mode: preserve

    - name: Levantar servicios con docker-compose
      shell: docker-compose up -d
      args:
        chdir: /srv/docker/web
